# Generated by Django 3.2.9 on 2021-12-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211128_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
